// components/whitepaper-short/copy.es.ts
// Spanish mirror of copy.en.ts. Same shape; translated strings.

import type { CodeToken, ReceiptRow, Shield } from './copy.en'

export const COPY_ES = {
  s1: {
    eyebrow: '· v5.1 · Base Sepolia · Modelo ClaimBond',
    h1Pre: 'Seguro para los agentes que nunca duermen — ',
    h1Italic: 'resuelto por oráculos, quemado por código.',
    sub: 'Lumina es un protocolo de seguro paramétrico on-chain en Base L2. Cada prima en USDC compra y quema $LUMINA de forma permanente. Cada póliza activada acuña un bono fijado en USD, redimible en 24 meses. Construido para agentes de IA autónomos que necesitan un payout en menos de un minuto.',
    btnPrimary: 'Lanzar app →',
    btnGhost: 'Leer whitepaper completo',
    feedLabel: 'Feed de quema · en vivo',
  },
  s2: {
    eyebrow: '02 / 10 · La brecha',
    h2Pre: 'El seguro cripto existente nunca fue construido ',
    h2Italic: 'para agentes autónomos.',
    p1: 'Nexus Mutual, InsurAce, Sherlock — todos los protocolos generales de seguro cripto usan reclamaciones discrecionales. Ocurre un evento, se reúne un comité, el pago se emite días o semanas después. Esa cadencia es incompatible con bots que liquidan, rebalancean y cubren posiciones dentro de un solo bloque.',
    p2: 'Un agente autónomo no puede llenar un formulario de reclamación. No puede discutir con un comité. No puede sobrevivir una votación de 7 días sobre si el depeg "realmente" sucedió. Necesita un trigger objetivo, firmado por un oráculo, y un pago que se ejecute dentro de la misma transacción que confirma la pérdida.',
    cards: [
      { ts: '2024-08-05', asset: 'BTC',   line: 'Flash crash −7% en 12 min — todos los bots apalancados fueron liquidados' },
      { ts: '2023-03-11', asset: 'USDC',  line: 'Perdió la paridad a $0.87 — los bots de yield no pudieron salir a tiempo' },
      { ts: '2022-06-13', asset: 'stETH', line: 'Liquidez drenada — los prestatarios de Aave fueron liquidados en masa' },
    ],
  },
  s3: {
    eyebrow: '03 / 10 · Tres pasos de la prima al payoff',
    h2: 'De la prima al payoff en tres pasos on-chain.',
    steps: [
      { glyph: '◇', title: 'Comprar', call: 'purchasePolicy(productId, coverage)',          body: 'Un agente elige uno de los 6 flash shields V5.3 y paga una prima en USDC. La wallet relayer paga el gas; el agente solo paga la prima.' },
      { glyph: '◆', title: 'Activar', call: 'submitTrigger(policyId, oracleProof)',         body: 'Cualquiera — agente, keeper, bot MEV — puede enviar un PriceProof firmado EIP-712. Si la condición paramétrica se cumple, el pago se ejecuta en la misma transacción.' },
      { glyph: '◈', title: 'Redimir', call: 'BondVault.redeemBond(epochId, usdAmount)',     body: 'La póliza activada acuña ClaimBonds ERC-1155 con valor nominal de $1. Mantén hasta vencimiento (730 días), o vende temprano en el marketplace secundario con descuento.' },
    ],
    payoff: '→ ClaimBond · valor nominal $1 · vencimiento 730d',
  },
  s4: {
    eyebrow: '04 / 10 · Ciclo de vida',
    h2Pre: 'De la prima al payout: ',
    h2Italic: 'seis pasos, dos finales.',
    lede: 'Cada posición Lumina recorre el mismo camino de seis pasos. La prima se paga en USDC y quema $LUMINA al entrar. Si el trigger se dispara, se acuña un ClaimBond. Desde ahí el holder elige uno de dos finales — esperar 730 días para recibir $LUMINA al vencimiento, o vender ahora en el marketplace secundario por USDC.',
    steps: [
      { title: 'Comprar póliza (USDC)',         body: 'Pagás una pequeña prima en USDC. Se enruta al AdaptiveFeeDistributor: 85% al TWAPBurner — compra y quema $LUMINA en Uniswap V3 — y 8/2/5% reparte treasury/ops/founder. El supply se reduce inmediatamente.' },
      { title: 'Trigger se dispara',            body: 'El oráculo observa el activo cubierto. Si la condición de trigger se cumple dentro de la ventana, la póliza queda activada y un ClaimBond es acuñable.' },
      { title: 'ClaimBond acuñado (ERC-1155)',  body: 'Acuñado al holder, indexado por epoch. Valor nominal $1 por unidad. Vencimiento: 730 días.' },
      { title: 'Elegís: esperar O vender',      body: 'Mantener el bono hasta el vencimiento para recibir $LUMINA, o listarlo en el marketplace secundario hoy por USDC.' },
      { title: 'Esperar 730d → $LUMINA',        body: 'redeemBond() lee el oráculo y acuña luminaAmount = usdAmount / LUMINA_price al holder. Capturás el upside si $LUMINA aprecia.' },
      { title: 'O vender ahora → USDC',         body: 'Listás en el marketplace secundario con descuento. El comprador paga USDC. Fee 2% — enrutado por el AdaptiveFeeDistributor con el mismo split 85/8/2/5.' },
    ],
    example: {
      label: 'Ejemplo trabajado',
      body: 'Prima de $3 USDC cubre $800 — Flash BTC 1h. El trigger se dispara. Un ClaimBond de 800 unidades es acuñado al wallet (ERC-1155, $1 nominal, vencimiento 730d).',
      waitLabel: 'Camino A · esperar 730d (LUMINA = $0.50)',
      waitOutcome: '1.600 LUMINA',
      sellLabel: 'Camino B · vender ahora (~70% del nominal)',
      sellOutcome: '~$560 USDC',
    },
    truth: 'Prima = USDC · Trade en marketplace = USDC · Redención al vencimiento = $LUMINA',
  },
  s5: {
    eyebrow: '05 / 10 · Seis flash shields paramétricos',
    h2Pre: 'Triggers específicos. Activos específicos. ',
    h2Italic: 'Ventanas de tiempo específicas.',
    lede: 'Cada flash shield V5.3 es BaseFlashShield + un FlashShieldAdapter UUPS-upgradeable que valida un drop desde el precio de compra dentro de una ventana fija. El registro on-chain de productos usa nombres canónicos del tipo FLASHBTC1H-001 — el productId que pasa el caller es el keccak256 de ese string.',
    shields: [
      { glyph: '₿', asset: 'BTC',  title: 'Flash BTC 1h',  trigger: 'BTC −2.5% / 1h',  pill: '1h',  canonical: 'FLASHBTC1H-001', literal: 'BTC' },
      { glyph: '₿', asset: 'BTC',  title: 'Flash BTC 24h', trigger: 'BTC −6% / 24h',   pill: '24h', canonical: 'FLASHBTC24-001', literal: 'BTC' },
      { glyph: '₿', asset: 'BTC',  title: 'Flash BTC 48h', trigger: 'BTC −10% / 48h',  pill: '48h', canonical: 'FLASHBTC48-001', literal: 'BTC' },
      { glyph: 'Ξ', asset: 'ETH',  title: 'Flash ETH 1h',  trigger: 'ETH −4% / 1h',    pill: '1h',  canonical: 'FLASHETH1H-001', literal: 'ETH' },
      { glyph: 'Ξ', asset: 'ETH',  title: 'Flash ETH 24h', trigger: 'ETH −8.5% / 24h', pill: '24h', canonical: 'FLASHETH24-001', literal: 'ETH' },
      { glyph: 'Ξ', asset: 'ETH',  title: 'Flash ETH 48h', trigger: 'ETH −14% / 48h',  pill: '48h', canonical: 'FLASHETH48-001', literal: 'ETH' },
    ] satisfies Shield[],
  },
  s6: {
    eyebrow: '06 / 10 · Tokenomics',
    h2Pre: '100 millones de $LUMINA. Fijo para siempre. ',
    h2Italic: 'Siempre disminuyendo.',
    lede: 'LuminaTokenV2 es un token ERC-20 + ERC-20Burnable. No tiene función de mint. El constructor impone totalSupply() == MAX_SUPPLY inmediatamente después de la distribución de génesis. Desde ese momento, el supply solo disminuye.',
    donut: { center: '100.000.000', centerSub: 'LUMINA · Fijo' },
    legend: [
      { label: 'Reserva de Bonds', val: '70 M', pct: 70, color: 'var(--rd-accent)' },
      { label: 'Liquidez',         val: '14 M', pct: 14, color: 'var(--rd-accent-2)' },
      { label: 'Fundadores',       val: '8 M',  pct: 8,  color: '#f59e0b' },
      { label: 'LBP',              val: '5 M',  pct: 5,  color: '#ec4899' },
      { label: 'Tesoro',           val: '3 M',  pct: 3,  color: '#22d3ee' },
    ],
    flowTitle: 'Flujo deflacionario',
    flow: [
      { num: '01', title: 'Prima pagada',                meta: 'USDC' },
      { num: '02', title: 'TWAPBurner.receivePremium',   meta: '100%' },
      { num: '03', title: 'Uniswap V3',                  meta: 'USDC → LUMINA' },
      { num: '04', title: '0xdead',                      meta: 'quema permanente' },
    ],
  },
  s7: {
    eyebrow: '07 / 10 · Quema adaptativa',
    h2Pre: 'Dieciséis regímenes de quema. ',
    h2Italic: 'La matriz decide a dónde va cada prima.',
    lede: 'El TWAPBurner no siempre quema directamente. Antes de comprar LUMINA, el burner consulta AdaptiveFeeDistributor. El split es una matriz 4×4 indexada por solvencia × momentum, con 16 celdas pre-ajustadas. HEALTHY × STABLE es el régimen por defecto; CRISIS × CRASH detiene la quema completamente y reserva 96% del USDC entrante para un buyback defensivo.',
    rowLabels: ['ULTRA', 'HEALTHY', 'STRESSED', 'CRISIS'],
    colLabels: ['RALLY', 'STABLE', 'DECLINE', 'CRASH'],
    matrix: [
      [[9500,0,0,500],     [9000,500,0,500],   [8500,1000,0,500],  [7500,2000,0,500]],
      [[9000,500,0,500],   [8500,800,200,500], [7000,2100,200,700],[5500,3500,200,800]],
      [[7500,1800,200,500],[5500,3500,200,800],[3800,5500,200,500],[1800,7500,200,500]],
      [[4800,4500,200,500],[2800,6500,200,500],[800,8500,200,500], [0,9600,200,200]],
    ] as const,
    barLabels: ['quema', 'buyback', 'ops', 'mant'],
    defaultLabel: 'DEFAULT',
    selectionHint: 'Toca cualquier celda para inspeccionar el split de 4 canales.',
    callout: {
      title: 'Estado en Sepolia',
      body: 'El momentum se mantiene neutral (10000 bps) en Sepolia hasta que despliegue un pool LUMINA/USDC profundo. La matriz de 16 celdas corre solo sobre su eje de solvencia — en runtime colapsa a la columna STABLE. El comportamiento completo de 16 cuadrantes se activa cuando el pool, el módulo de momentum-oracle en release/v5.1-pre-mainnet, y el BuybackSpender se entreguen juntos.',
    },
  },
  s8: {
    eyebrow: '08 / 10 · Construido para integración autónoma',
    h2Pre: 'Una llamada HTTP. El relayer paga el gas. ',
    h2Italic: 'El agente solo tiene USDC.',
    lede: 'Los mismos contratos que mueven la app humana exponen una API REST delgada. POST /api/v1/policies firma purchasePolicyFor on-chain en nombre del agente. Sin wallet de gas, sin popup, sin KYC. Misma mecánica de bonos. Misma resolución por oráculo.',
    codeFile: 'agent.ts',
    codeLines: [
      { type: 'kw', text: 'import' }, { type: 'txt', text: ' { ' }, { type: 'id', text: 'LuminaClient' }, { type: 'txt', text: ' } ' }, { type: 'kw', text: 'from' }, { type: 'txt', text: ' ' }, { type: 'str', text: "'@lumina-org/sdk'" }, { type: 'br' },
      { type: 'br' },
      { type: 'kw', text: 'const' }, { type: 'txt', text: ' ' }, { type: 'id', text: 'lumina' }, { type: 'txt', text: ' = ' }, { type: 'kw', text: 'new' }, { type: 'txt', text: ' ' }, { type: 'id', text: 'LuminaClient' }, { type: 'txt', text: '({ apiKey: process.env.' }, { type: 'id', text: 'LUMINA_API_KEY' }, { type: 'txt', text: ' })' }, { type: 'br' },
      { type: 'br' },
      { type: 'kw', text: 'const' }, { type: 'txt', text: ' ' }, { type: 'id', text: 'policy' }, { type: 'txt', text: ' = ' }, { type: 'kw', text: 'await' }, { type: 'txt', text: ' lumina.policies.' }, { type: 'id', text: 'purchase' }, { type: 'txt', text: '({' }, { type: 'br' },
      { type: 'txt', text: '  productName:    ' }, { type: 'str', text: "'FLASHBTC1H-001'" }, { type: 'txt', text: ',' }, { type: 'br' },
      { type: 'txt', text: '  buyer:          ' }, { type: 'str', text: "'0xYourAgentWallet'" }, { type: 'txt', text: ',' }, { type: 'br' },
      { type: 'txt', text: '  coverageAmount: ' }, { type: 'str', text: "'100000000'" }, { type: 'txt', text: ',' }, { type: 'comment', text: '  // $100, 6-dec USDC (mín. on-chain)' }, { type: 'br' },
      { type: 'txt', text: '})' }, { type: 'br' },
      { type: 'br' },
      { type: 'id', text: 'console' }, { type: 'txt', text: '.' }, { type: 'id', text: 'log' }, { type: 'txt', text: '(policy.policyId, policy.txHash)' }, { type: 'br' },
      { type: 'comment', text: "// → '0x9f2e…', '0xab4d…'" },
    ] satisfies CodeToken[],
    receiptTitle: 'lumina-cli · recibo',
    receipt: [
      { k: 'policyId',     v: '0x9f2e6c...' },
      { k: 'txHash',       v: '0xab4d1d...' },
      { k: 'productName',  v: 'FLASHBTC1H-001' },
      { k: 'asset',        v: 'BTC (auto-resuelto)' },
      { k: 'premium',      v: '$0.24 USDC' },
      { k: 'relayerPaid',  v: 'true', highlight: true, note: 'el agente pagó 0 gas' },
      { k: 'gasHeld',      v: 'false' },
      { k: 'bondEpochId',  v: '202805 (mayo 2028)' },
    ] satisfies ReceiptRow[],
    pills: ['wallet de gas', 'popup MetaMask', 'formulario KYC'],
  },
  s9: {
    eyebrow: '09 / 10 · Estado en vivo',
    h2Pre: 'Todo lo que está en este whitepaper está on-chain ',
    h2Italic: 'ahora mismo.',
    lede: 'Estos son los contratos con los que la API y el frontend en producción hablan hoy. Verifica siempre contra /health antes de integrar — un redeploy invalida silenciosamente el .env de ayer.',
    statLabels: ['ALTURA DE BLOQUE', 'BALANCE DEL RELAYER', 'TOTAL LUMINA QUEMADO', 'CONTRATOS VERIFICADOS'],
    fallbackBurned: 1284503,
    addressTable: { head: ['Contrato', 'Dirección'] },
    healthFooter: 'Fuente · /health · Base Sepolia · chainId 84532',
  },
  s10: {
    eyebrow: '10 / 10 · Comenzar ahora',
    h2Pre: '¿Listo para asegurar ',
    h2Italic: 'los bots que nunca duermen?',
    btn1: 'Lanzar la app →',
    btn2: 'Leer el whitepaper completo →',
    btn3: 'Leer los docs del SDK',
    tagline: 'Construido en Base L2 · Deflacionario por diseño',
  },
} as const

export type CopyES = typeof COPY_ES
